-- ============================================================
-- 005_seed_minimal_rental_catalog.sql
--
-- Transitional bridge seed:
-- Seed the current runtime rental-capable mock products/SKUs into the DB so
-- `rental_bookings` can reference real catalog rows while the storefront is
-- still reading mock data.
--
-- Scope intentionally stays minimal:
--   - current rental-capable runtime fixtures only
--   - products + product_skus only
--   - rerun-safe upserts by primary key
-- ============================================================

INSERT INTO public.products (
  id,
  slug,
  type,
  name_th,
  name_en,
  description_th,
  description_en,
  category_keys,
  brand,
  thumbnail_url,
  supplier_ids,
  rental_min_days,
  rental_max_days,
  rental_buffer_days,
  store_location_ids
)
VALUES
  (
    'catalog-prod-101',
    'bosch-rotary-hammer-kit-series',
    'hybrid',
    'สว่านโรตารี่ Bosch ชุดคิท',
    'Bosch Rotary Hammer Kit Series',
    'สินค้าทดลองแบบ hybrid มีหลาย SKU สำหรับทั้งซื้อและเช่า ใช้ทดสอบ flow ใหม่ของสินค้า/SKU/cart.',
    'Hybrid multi-SKU fixture for testing the new product, SKU, booking, and cart flow.',
    ARRAY['mechanic_tools', 'm01'],
    'Bosch',
    'https://placehold.co/400x400/1565C0/FFFFFF?text=Bosch+Kit&font=roboto',
    ARRAY['sup-001', 'sup-002'],
    1,
    30,
    1,
    ARRAY['store-001', 'store-002']
  ),
  (
    'catalog-prod-103',
    'bosch-laser-level-rental-pack',
    'rental',
    'เลเซอร์วัดระดับ Bosch สำหรับเช่า',
    'Bosch Laser Level Rental Pack',
    'สินค้าทดลองแบบ rental multi-SKU สำหรับทดสอบ flow การจองพร้อมชุดอุปกรณ์เสริม.',
    'Rental-only multi-SKU fixture for testing booking flow with accessory bundles.',
    ARRAY['measuring_tools', 'me02'],
    'Bosch',
    'https://placehold.co/400x400/2E7D32/FFFFFF?text=Laser+Rental&font=roboto',
    ARRAY['sup-001'],
    1,
    14,
    1,
    ARRAY['store-001']
  ),
  (
    'prod-001',
    'bosch-electric-drill-gsb-550',
    'hybrid',
    'สว่านไฟฟ้า Bosch GSB 550',
    'Bosch Electric Drill GSB 550',
    'สว่านกระแทกไฟฟ้า 550 วัตต์ เหมาะสำหรับงานเจาะคอนกรีต ไม้ และเหล็ก ใช้งานง่าย ทนทาน',
    '550W impact drill for concrete, wood and metal. Easy to use and durable.',
    ARRAY['mechanic_tools', 'm01'],
    'Bosch',
    'https://placehold.co/400x400/1565C0/FFFFFF?text=Bosch+Drill&font=roboto',
    ARRAY['sup-001', 'sup-002'],
    1,
    30,
    1,
    ARRAY['store-001', 'store-002']
  ),
  (
    'prod-002',
    '3m-safety-helmet-h-700',
    'hybrid',
    'หมวกนิรภัย 3M H-700',
    '3M Safety Helmet H-700',
    'หมวกนิรภัยมาตรฐาน มีระบบรองในปรับขนาดได้ น้ำหนักเบา ระบายอากาศดี',
    'Standard safety helmet with adjustable suspension. Lightweight and well-ventilated.',
    ARRAY['safety_equipment', 's05'],
    '3M',
    'https://placehold.co/400x400/D32F2F/FFFFFF?text=3M+Helmet&font=roboto',
    ARRAY['sup-001', 'sup-005'],
    1,
    90,
    0,
    ARRAY['store-001']
  ),
  (
    'prod-003',
    'makita-angle-grinder-ga4030',
    'hybrid',
    'เครื่องเจียร Makita GA4030',
    'Makita Angle Grinder GA4030',
    'เครื่องเจียร 4 นิ้ว 720 วัตต์ รอบสูง ตัดเหล็ก ขัดผิว ใช้งานหนักได้',
    '4-inch 720W angle grinder. High RPM for cutting and grinding metal.',
    ARRAY['mechanic_tools', 'm03'],
    'Makita',
    'https://placehold.co/400x400/00897B/FFFFFF?text=Makita+Grinder&font=roboto',
    ARRAY['sup-002', 'sup-006'],
    1,
    30,
    1,
    ARRAY['store-001', 'store-003']
  ),
  (
    'prod-006',
    'hilti-rotary-hammer-te-2',
    'hybrid',
    'สว่านโรตารี่ Hilti TE 2',
    'Hilti Rotary Hammer TE 2',
    'สว่านโรตารี่ 710 วัตต์ ระบบ SDS-plus เจาะคอนกรีตได้ลึก ทนทานระดับมืออาชีพ',
    '710W SDS-plus rotary hammer. Deep concrete drilling. Professional grade durability.',
    ARRAY['mechanic_tools', 'm01'],
    'Hilti',
    'https://placehold.co/400x400/D50000/FFFFFF?text=Hilti+Hammer&font=roboto',
    ARRAY['sup-001', 'sup-006'],
    1,
    60,
    2,
    ARRAY['store-001']
  ),
  (
    'prod-008',
    'mitutoyo-digital-caliper-150mm',
    'hybrid',
    'เวอร์เนียร์ดิจิตอล Mitutoyo 150mm',
    'Mitutoyo Digital Caliper 150mm',
    'เวอร์เนียร์ดิจิตอล ความละเอียด 0.01mm พร้อมกล่องเก็บ แบตเตอรี่อายุยาว',
    'Digital caliper 0.01mm resolution with storage case. Long battery life.',
    ARRAY['measuring_tools', 'me03'],
    'Mitutoyo',
    'https://placehold.co/400x400/37474F/FFFFFF?text=Mitutoyo+Caliper&font=roboto',
    ARRAY['sup-004'],
    1,
    14,
    1,
    ARRAY['store-002']
  ),
  (
    'prod-010',
    'dewalt-cordless-impact-driver-dcf887',
    'hybrid',
    'สว่านกระแทกไร้สาย DeWalt DCF887',
    'DeWalt Cordless Impact Driver DCF887',
    'สว่านกระแทกไร้สาย 20V Max แรงบิด 205Nm 3 ระดับความเร็ว น้ำหนักเบา',
    '20V Max cordless impact driver. 205Nm torque, 3-speed settings, lightweight.',
    ARRAY['mechanic_tools', 'm01'],
    'DeWalt',
    'https://placehold.co/400x400/F9A825/000000?text=DeWalt+Impact&font=roboto',
    ARRAY['sup-002', 'sup-003'],
    1,
    30,
    1,
    ARRAY['store-001', 'store-003']
  ),
  (
    'prod-011',
    'fluke-multimeter-117',
    'hybrid',
    'มัลติมิเตอร์ Fluke 117',
    'Fluke Multimeter 117',
    'มัลติมิเตอร์ดิจิตอล True RMS วัดไฟ AC/DC กระแส ความต้านทาน ตรวจจับแรงดัน',
    'True RMS digital multimeter. AC/DC voltage, current, resistance, voltage detection.',
    ARRAY['measuring_tools', 'me04'],
    'Fluke',
    'https://placehold.co/400x400/FDD835/000000?text=Fluke+117&font=roboto',
    ARRAY['sup-004'],
    1,
    14,
    1,
    ARRAY['store-002']
  ),
  (
    'prod-013',
    'bosch-laser-level-gll-3-80',
    'hybrid',
    'เลเซอร์วัดระดับ Bosch GLL 3-80',
    'Bosch Laser Level GLL 3-80',
    'เลเซอร์วัดระดับ 3 ระนาบ 360° ระยะ 30 เมตร แม่นยำสูง พร้อมกล่องเก็บ',
    '3-plane 360° laser level. 30m range, high accuracy. Includes carrying case.',
    ARRAY['measuring_tools', 'me02'],
    'Bosch',
    'https://placehold.co/400x400/1565C0/FFFFFF?text=Bosch+Laser&font=roboto',
    ARRAY['sup-001', 'sup-002'],
    1,
    30,
    1,
    ARRAY['store-001', 'store-002']
  ),
  (
    'prod-014',
    'makita-circular-saw-hs7601',
    'hybrid',
    'เลื่อยวงเดือน Makita HS7601',
    'Makita Circular Saw HS7601',
    'เลื่อยวงเดือน 7 นิ้ว 1200W ตัดไม้ ไม้อัด พลาสติก ปรับมุมองศาได้',
    '7-inch 1200W circular saw for wood, plywood, plastic. Adjustable bevel angle.',
    ARRAY['mechanic_tools', 'm03'],
    'Makita',
    'https://placehold.co/400x400/00897B/FFFFFF?text=Makita+Saw&font=roboto',
    ARRAY['sup-002', 'sup-006'],
    1,
    30,
    1,
    ARRAY['store-001', 'store-003']
  ),
  (
    'prod-019',
    'msa-full-body-harness-v-gard',
    'hybrid',
    'เข็มขัดนิรภัยเต็มตัว MSA V-Gard',
    'MSA Full Body Harness V-Gard',
    'เข็มขัดนิรภัยเต็มตัว 5 จุดรัด สำหรับงานที่สูง มาตรฐาน EN 361 ปรับขนาดได้',
    '5-point full body harness for working at height. EN 361 certified, adjustable.',
    ARRAY['safety_equipment', 's01'],
    'MSA',
    'https://placehold.co/400x400/2E7D32/FFFFFF?text=MSA+Harness&font=roboto',
    ARRAY['sup-005', 'sup-001'],
    1,
    90,
    2,
    ARRAY['store-001', 'store-002', 'store-003']
  )
ON CONFLICT (id) DO UPDATE
SET
  slug = EXCLUDED.slug,
  type = EXCLUDED.type,
  name_th = EXCLUDED.name_th,
  name_en = EXCLUDED.name_en,
  description_th = EXCLUDED.description_th,
  description_en = EXCLUDED.description_en,
  category_keys = EXCLUDED.category_keys,
  brand = EXCLUDED.brand,
  thumbnail_url = EXCLUDED.thumbnail_url,
  supplier_ids = EXCLUDED.supplier_ids,
  rental_min_days = EXCLUDED.rental_min_days,
  rental_max_days = EXCLUDED.rental_max_days,
  rental_buffer_days = EXCLUDED.rental_buffer_days,
  store_location_ids = EXCLUDED.store_location_ids,
  updated_at = now();

INSERT INTO public.product_skus (
  id,
  product_id,
  label_th,
  label_en,
  price,
  original_price,
  discount_percent,
  rental_deposit,
  rental_daily,
  rental_weekly,
  rental_monthly,
  stock,
  rental_stock,
  reserved_stock
)
VALUES
  ('catalog-sku-101-standard', 'catalog-prod-101', 'ชุดมาตรฐาน', 'Standard Kit', 4900, 5400, 9, 3500, 350, 2100, 6900, 12, 4, 1),
  ('catalog-sku-101-pro', 'catalog-prod-101', 'ชุดโปร', 'Pro Kit', 6900, 7600, 9, 5000, 490, 2940, 9600, 8, 3, 1),
  ('catalog-sku-103-standard', 'catalog-prod-103', 'เฉพาะตัวเครื่อง', 'Tool Only', 0, 0, 0, 4000, 450, 2600, 8800, 0, 5, 2),
  ('catalog-sku-103-tripod', 'catalog-prod-103', 'พร้อมขาตั้ง', 'With Tripod', 0, 0, 0, 5000, 520, 3050, 9900, 0, 3, 1),
  ('sku-001-default', 'prod-001', 'มาตรฐาน', 'Standard', 2125, 2500, 15, 3000, 200, 1200, 4000, 25, 5, 2),
  ('sku-002-default', 'prod-002', 'มาตรฐาน', 'Standard', 350, 350, 0, 500, 30, 150, 450, 150, 20, 5),
  ('sku-003-default', 'prod-003', 'มาตรฐาน', 'Standard', 1701, 1890, 10, 2500, 180, 1000, 3500, 12, 3, 1),
  ('sku-006-default', 'prod-006', 'มาตรฐาน', 'Standard', 12500, 12500, 0, 5000, 500, 3000, 10000, 5, 2, 1),
  ('sku-008-default', 'prod-008', 'มาตรฐาน', 'Standard', 2880, 3200, 10, 4000, 250, 1500, 5000, 15, 4, 1),
  ('sku-010-default', 'prod-010', 'มาตรฐาน', 'Standard', 6072, 6900, 12, 5000, 350, 2000, 7000, 18, 6, 2),
  ('sku-011-default', 'prod-011', 'มาตรฐาน', 'Standard', 8500, 8500, 0, 6000, 400, 2400, 8000, 8, 3, 1),
  ('sku-013-default', 'prod-013', 'มาตรฐาน', 'Standard', 15105, 15900, 5, 8000, 600, 3500, 12000, 6, 2, 1),
  ('sku-014-default', 'prod-014', 'มาตรฐาน', 'Standard', 4200, 4200, 0, 4000, 300, 1800, 6000, 10, 4, 1),
  ('sku-019-default', 'prod-019', 'มาตรฐาน', 'Standard', 5500, 5500, 0, 3000, 250, 1500, 5000, 30, 8, 3)
ON CONFLICT (id) DO UPDATE
SET
  product_id = EXCLUDED.product_id,
  label_th = EXCLUDED.label_th,
  label_en = EXCLUDED.label_en,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  discount_percent = EXCLUDED.discount_percent,
  rental_deposit = EXCLUDED.rental_deposit,
  rental_daily = EXCLUDED.rental_daily,
  rental_weekly = EXCLUDED.rental_weekly,
  rental_monthly = EXCLUDED.rental_monthly,
  stock = EXCLUDED.stock,
  rental_stock = EXCLUDED.rental_stock,
  reserved_stock = EXCLUDED.reserved_stock,
  updated_at = now();