-- Central dictionary for catalog tags and search keywords

CREATE TABLE IF NOT EXISTS public.catalog_terms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('tag', 'search_keyword')),
  normalized_value TEXT NOT NULL,
  display_value TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT catalog_terms_kind_normalized_value_key UNIQUE (kind, normalized_value),
  CONSTRAINT catalog_terms_normalized_value_chk CHECK (char_length(trim(normalized_value)) > 0),
  CONSTRAINT catalog_terms_display_value_chk CHECK (char_length(trim(display_value)) > 0)
);

COMMENT ON TABLE public.catalog_terms IS 'Central autocomplete dictionary for admin-authored product tags and search keywords.';
COMMENT ON COLUMN public.catalog_terms.kind IS 'Dictionary namespace: tag or search_keyword.';
COMMENT ON COLUMN public.catalog_terms.normalized_value IS 'Normalized unique key used for dedupe and lookup.';
COMMENT ON COLUMN public.catalog_terms.display_value IS 'Human-facing label shown in admin autocomplete UIs.';
COMMENT ON COLUMN public.catalog_terms.is_active IS 'If false, keep historical term but hide it from autocomplete suggestions.';

CREATE INDEX IF NOT EXISTS idx_catalog_terms_kind_active_display
  ON public.catalog_terms (kind, is_active, display_value);

DROP TRIGGER IF EXISTS set_catalog_terms_updated_at ON public.catalog_terms;

CREATE TRIGGER set_catalog_terms_updated_at
  BEFORE UPDATE ON public.catalog_terms
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE OR REPLACE FUNCTION public.normalize_catalog_tag_term(raw_value TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT trim(BOTH '_' FROM regexp_replace(
    regexp_replace(
      regexp_replace(lower(coalesce(raw_value, '')), '[-\s]+', '_', 'g'),
      '[^a-z0-9_-]+',
      '',
      'g'
    ),
    '_{2,}',
    '_',
    'g'
  ));
$$;

CREATE OR REPLACE FUNCTION public.normalize_catalog_search_keyword_term(raw_value TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT lower(trim(regexp_replace(coalesce(raw_value, ''), '\s+', ' ', 'g')));
$$;

CREATE OR REPLACE FUNCTION public.upsert_catalog_term(term_kind TEXT, raw_value TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  normalized TEXT;
  display TEXT;
BEGIN
  IF term_kind = 'tag' THEN
    normalized := public.normalize_catalog_tag_term(raw_value);
    display := normalized;
  ELSIF term_kind = 'search_keyword' THEN
    normalized := public.normalize_catalog_search_keyword_term(raw_value);
    display := trim(regexp_replace(coalesce(raw_value, ''), '\s+', ' ', 'g'));
  ELSE
    RAISE EXCEPTION 'Unsupported catalog term kind: %', term_kind;
  END IF;

  IF normalized IS NULL OR char_length(normalized) = 0 THEN
    RETURN;
  END IF;

  IF display IS NULL OR char_length(display) = 0 THEN
    RETURN;
  END IF;

  INSERT INTO public.catalog_terms (kind, normalized_value, display_value)
  VALUES (term_kind, normalized, display)
  ON CONFLICT (kind, normalized_value) DO UPDATE
  SET
    is_active = TRUE,
    updated_at = timezone('utc', now()),
    display_value = CASE
      WHEN public.catalog_terms.kind = 'search_keyword'
        AND EXCLUDED.display_value <> ''
      THEN EXCLUDED.display_value
      ELSE public.catalog_terms.display_value
    END;
END;
$$;

COMMENT ON FUNCTION public.upsert_catalog_term IS 'Upserts a normalized tag/search keyword into the central catalog_terms dictionary.';

CREATE OR REPLACE FUNCTION public.sync_catalog_terms_from_product()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  raw_value TEXT;
BEGIN
  FOREACH raw_value IN ARRAY COALESCE(NEW.tag_keys, ARRAY[]::TEXT[])
  LOOP
    PERFORM public.upsert_catalog_term('tag', raw_value);
  END LOOP;

  FOREACH raw_value IN ARRAY COALESCE(NEW.search_keywords, ARRAY[]::TEXT[])
  LOOP
    PERFORM public.upsert_catalog_term('search_keyword', raw_value);
  END LOOP;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS products_after_sync_catalog_terms_trg ON public.products;

CREATE TRIGGER products_after_sync_catalog_terms_trg
  AFTER INSERT OR UPDATE OF tag_keys, search_keywords
  ON public.products
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_catalog_terms_from_product();

INSERT INTO public.catalog_terms (kind, normalized_value, display_value)
SELECT DISTINCT
  'tag',
  public.normalize_catalog_tag_term(raw_value),
  public.normalize_catalog_tag_term(raw_value)
FROM public.products p,
LATERAL unnest(COALESCE(p.tag_keys, ARRAY[]::TEXT[])) AS raw_value
WHERE char_length(public.normalize_catalog_tag_term(raw_value)) > 0
ON CONFLICT (kind, normalized_value) DO UPDATE
SET is_active = TRUE,
    updated_at = timezone('utc', now());

INSERT INTO public.catalog_terms (kind, normalized_value, display_value)
SELECT DISTINCT
  'search_keyword',
  public.normalize_catalog_search_keyword_term(raw_value),
  trim(regexp_replace(coalesce(raw_value, ''), '\s+', ' ', 'g'))
FROM public.products p,
LATERAL unnest(COALESCE(p.search_keywords, ARRAY[]::TEXT[])) AS raw_value
WHERE char_length(public.normalize_catalog_search_keyword_term(raw_value)) > 0
ON CONFLICT (kind, normalized_value) DO UPDATE
SET is_active = TRUE,
    updated_at = timezone('utc', now()),
    display_value = EXCLUDED.display_value;