/**
 * Partner Directory — public-facing types.
 *
 * These types are safe to use in public pages and public API responses.
 * Private admin fields (kyc_documents, verified_notes, internal_notes)
 * are NEVER present here.
 */

export type PartnerDirectoryType = "store" | "service" | "contractor";
export type PartnerEntityType = "individual" | "organization";

/**
 * Machine-readable business hours preset keys.
 * Mirrors the DB CHECK constraint on partner_profiles.business_hours_preset_key (migration 098).
 * NULL means custom free text, unspecified, or legacy text-only row — excluded from Open Now.
 */
export const BUSINESS_HOURS_PRESET_KEYS = [
  "open_24h",
  "by_appointment",
  "everyday_0900_1800",
  "mon_fri_0900_1800",
  "mon_sat_0900_1800",
  "sat_sun_0900_1800",
] as const;

export type PartnerBusinessHoursPresetKey =
  (typeof BUSINESS_HOURS_PRESET_KEYS)[number];

// ── Partner Content Blocks ────────────────────────────────────────────────────

/** Common fields shared by all partner content block types. */
interface PartnerContentBlockBase {
  /** UUID generated by the frontend via crypto.randomUUID(). */
  id: string;
  type: "text" | "drive_doc" | "youtube";
  /** Visibility gate. Public API only returns blocks where isVisible = true. */
  isVisible: boolean;
}

/** Plain-text content section. No HTML or markdown. */
export interface PartnerTextBlock extends PartnerContentBlockBase {
  type: "text";
  /** Optional section heading. Max 120 chars. */
  title?: string;
  /** Required body. Plain text only — use whitespace-pre-line for rendering. Max 5000 chars. */
  body: string;
}

/** Linked Google Drive / Docs document. */
export interface PartnerDriveDocBlock extends PartnerContentBlockBase {
  type: "drive_doc";
  /** Required document label. Max 120 chars. */
  title: string;
  /** HTTPS URL — must be drive.google.com or docs.google.com. */
  url: string;
  /** Always "google_drive". Server-side forced; client value ignored. */
  provider: "google_drive";
}

/** Embedded YouTube video. */
export interface PartnerYoutubeBlock extends PartnerContentBlockBase {
  type: "youtube";
  /** Optional video title. Max 120 chars. */
  title?: string;
  /** Original YouTube URL as entered by admin. */
  url: string;
  /** Extracted server-side from url. Client-supplied value is overwritten. */
  videoId: string;
}

/** Discriminated union of all MVP content block types. */
export type PartnerContentBlock =
  | PartnerTextBlock
  | PartnerDriveDocBlock
  | PartnerYoutubeBlock;

/**
 * Display-only partner taxonomy item (migrations 116/117).
 * Mirrors the server `PublicPartnerTaxonomyItem`. No category id is exposed;
 * the label is resolved from the `partners.categories.${slug}` i18n key.
 */
export interface PartnerTaxonomyItem {
  slug: string;
  level: 0 | 1;
  isPrimary: boolean;
}

/**
 * Lightweight card shape — used in directory listing pages and the
 * Home Partner Network section.
 */
export interface PartnerCard {
  id: string;
  slug: string;
  directoryType: PartnerDirectoryType;
  entityType: PartnerEntityType;
  nameTh: string;
  nameEn: string | null;
  taglineTh: string | null;
  taglineEn: string | null;
  mainImageUrl: string | null;
  /** Square/portrait thumbnail image (card grid). Fallback: thumbnailImageUrl → coverImageUrl → mainImageUrl → placeholder. */
  thumbnailImageUrl: string | null;
  /** Wide banner cover image (detail hero). Fallback: coverImageUrl → mainImageUrl → placeholder. */
  coverImageUrl: string | null;
  mainCategoryKey: string | null;
  /** Controlled secondary category keys — share the same directoryType prefix as mainCategoryKey. */
  secondaryCategoryKeys: string[];
  /**
   * Display-only partner taxonomy (migrations 116/117). Empty when the partner
   * has no assignment. Primary first, then secondaries. No category ids exposed —
   * labels derive from `partners.categories.${slug}` client-side.
   */
  taxonomy: PartnerTaxonomyItem[];
  serviceAreas: string[];
  /** Machine-readable preset key. Null = custom/unspecified. Exposed for future Open Now badge. */
  businessHoursPresetKey: PartnerBusinessHoursPresetKey | null;
  isVerified: boolean;
  verifiedAt: string | null;
  isFeatured: boolean;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * Full detail shape — used on the public Partner Landing Page.
 * Extends PartnerCard with contact info, descriptions, map/hours, and content blocks.
 */
export interface PartnerDetail extends PartnerCard {
  descriptionTh: string | null;
  descriptionEn: string | null;
  contactPhone: string | null;
  contactEmail: string | null;
  lineId: string | null;
  lineUrl: string | null;
  mapsUrl: string | null;
  /** Display-only free text. NEVER used for Open Now logic. */
  businessHoursText: string | null;
  /** IANA timezone for business hours. MVP: always 'Asia/Bangkok'. */
  businessHoursTimezone: string;
  /**
   * Ordered content blocks for the public detail page.
   * Public API returns only isVisible=true blocks.
   * Not present on PartnerCard (list responses).
   */
  contentBlocks: PartnerContentBlock[];
}

/** Paginated listing response for the public directory. */
export interface PartnerListResponse {
  items: PartnerCard[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}
